### ISSUE TITLE
Cant new herokuapp

### ISSUE THREAD

**Issue by serkandyck** [malikov/Authenticate.me-Node-Server#3]
clone ur repository and push heroku heroku ps:scale web=1 all done but get error Application Error Here some logs

2015-08-13T13:39:19.723700+00:00 heroku[web.1]: Starting process with command `n
ode ./bin/www`
2015-08-13T13:39:25.578737+00:00 app[web.1]: /app/node_modules/express/lib/route
r/index.js:327
2015-08-13T13:39:25.578757+00:00 app[web.1]:     throw new Error(msg);
2015-08-13T13:39:25.578761+00:00 app[web.1]: Error: Router.use() requires callba
ck functions but got a [object Object]
2015-08-13T13:39:25.578759+00:00 app[web.1]:           ^
2015-08-13T13:39:25.578762+00:00 app[web.1]:     at Function.proto.use (/app/nod
e_modules/express/lib/router/index.js:327:11)
2015-08-13T13:39:25.578763+00:00 app[web.1]:     at Function.app.use (/app/node_
modules/express/lib/application.js:195:16)
2015-08-13T13:39:25.578765+00:00 app[web.1]:     at Object.<anonymous> (/app/app
.js:67:5)
2015-08-13T13:39:25.578766+00:00 app[web.1]:     at Module._compile (module.js:4
60:26)
2015-08-13T13:39:25.578767+00:00 app[web.1]:     at Object.Module._extensions..j
s (module.js:478:10)
2015-08-13T13:39:25.578769+00:00 app[web.1]:     at Module.load (module.js:355:3
2)
2015-08-13T13:39:25.578770+00:00 app[web.1]:     at Function.Module._load (modul
e.js:310:12)
2015-08-13T13:39:25.578771+00:00 app[web.1]:     at Module.require (module.js:36
5:17)
2015-08-13T13:39:25.578772+00:00 app[web.1]:     at require (module.js:384:17)
2015-08-13T13:39:25.578774+00:00 app[web.1]:     at Object.<anonymous> (/app/bin
/www:6:11)

**Comment by serkandyck** [comment]
problem solved not source code
